export const LOAD_LIST_STUDENT = "LOAD_LIST_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const DELETE_STUDENT ="DELETE_STUDENT";
export const SELECTED_STUDENT ="SELECTED_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const SEARCH_TERM ="SEARCH_TERM";
export const IS_CREATE_STUDENT ="IS_CREATE_STUDENT"